import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";



import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Sidebar from "@/components/shared/sidebar";
import Header from "@/components/shared/header";
import React from "react";
import AuthProvider from "@/components/shared/AppProvider";
import { Toaster } from "@/components/ui/toaster";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <Sidebar/>
            <div className="flex flex-col">
            <Header/>
            <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
            {children}
            <Toaster/>
            </main>
            </div>
          </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
